INSERT INTO USER (ID, FIRST_NAME, LAST_NAME, SSN, GENDER) VALUES (1, 'Victor', 'Paun', '1941024160054', 'MALE');
INSERT INTO ACCOUNT (ID, USERNAME, PASSWORD, EMAIL, USER_ROLE) VALUES  (1, 'vpaun',
'$2a$10$5ysE1CvqJLSXL5hFChyhFO4gwGIgYjaprBIcrxAgSfgJVhs0UVoTS', 'victorpaun20@yahoo.com', 'STUDENT');